### ISSUE TITLE
queue::has_capacity Requirements Not Documented

### ISSUE THREAD

**Issue by RobertLeahy** [boostorg/lockfree#35]
The constructors for `queue` do not document their requirements with respect to the `capacity` tag.

Moreover [in certain constructors a runtime assert (only present in debug mode) are used to verify the requirement](https://github.com/boostorg/lockfree/blob/8e98981c211be6a6970a5a954c0a50d4ab736c45/include/boost/lockfree/queue.hpp#L187). It shouldn't be necessary to build code in debug mode to discover what is logically a compile time constraint.

**Comment by austin-beer** [comment]
The reason for using runtime asserts is explained in #43.
