### ISSUE TITLE
change constructor (queue()) has_capacity assert to static assert

### ISSUE THREAD

**Issue by bansalnvn** [boostorg/lockfree#43]
https://github.com/boostorg/lockfree/blob/ffd91db4589fda2e5f843d0773dc3325baea88e0/include/boost/lockfree/queue.hpp#L188

This check for construction of the queue, if the capacity has been specified as the template parameter should be moved to static assert rather than having the run time assert.

**Comment by bansalnvn** [comment]
Yeah, I think currently `std::enable_if` or the `if constexpr` is needed. I will close the ticket for now. Thanks.

**Comment by austin-beer** [comment]
For the record, this is the commit that changed `BOOST_STATIC_ASSERT()` to `BOOST_ASSERT()` back in 2012: 505c1c04c18939cfd8fbf58386230ee78f4549ad
