### ISSUE TITLE
What is the use of the btiwise and in tagged_ptr_dcas::get_next_tag?

### ISSUE THREAD

**Issue by brunoczim** [boostorg/lockfree#47]
Here
https://github.com/boostorg/lockfree/blob/develop/include/boost/lockfree/detail/tagged_ptr_dcas.hpp#L107

What is the use of such bitwise and? This seems to be a no-op for me. In first place, because overflow is well-defined for `size_t` (wrapping). Doing `x & ~(size_t)0` is always `x`. In second place, because even if the overflow were not defined, the bitwise and would happen *after* the overflow, and UB would be invoked anyway.

**Comment by timblechmann** [comment]
msvc
https://github.com/boostorg/lockfree/commit/85fd0b135677e62a140f08bb169cbc7f78a7f8e1
