### ISSUE TITLE
Reconfiguring with BUILD_TESTING=OFF doesn't disable tests

### ISSUE THREAD

**Issue by pdimov** [boostorg/lockfree#97]
When Lockfree is configured with `cmake -DBUILD_TESTING=ON ..`, and then reconfigured with `cmake -DBUILD_TESTING=OFF .`, tests remain enabled. That's because `BUILD_TESTING` is only used once as the default value of `BOOST_LOCKFREE_BUILD_TESTS` and is ignored afterwards.

That's not how all other Boost libraries work; they check `BUILD_TESTING` directly and do not `add_subdirectory(test)` if it's off.

**Comment by timblechmann** [comment]
#96 should fix it
